# Generated by Django 4.1.7 on 2023-03-14 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallpapers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterField(
            model_name='wallpaper',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='wallpaper',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='wallpaper',
            name='thumbnail',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='wallpaper',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
