# Generated by Django 4.1.7 on 2023-03-14 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallpapers', '0002_alter_category_options_alter_wallpaper_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallpaper',
            name='image',
            field=models.ImageField(max_length=200, upload_to=''),
        ),
        migrations.AlterField(
            model_name='wallpaper',
            name='thumbnail',
            field=models.ImageField(blank=True, max_length=200, upload_to=''),
        ),
    ]
