# Generated by Django 4.1.7 on 2023-03-14 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallpapers', '0003_alter_wallpaper_image_alter_wallpaper_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallpaper',
            name='is_landscape',
            field=models.BooleanField(default=True),
        ),
    ]
