# Generated by Django 4.1.7 on 2023-03-14 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallpapers', '0005_wallpaper_is_premium'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallpaper',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
