# Generated by Django 4.1.7 on 2023-03-16 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallpapers', '0007_rename_description_wallpaper_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallpaper',
            name='slug',
            field=models.SlugField(blank=True, max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='wallpaper',
            name='title',
            field=models.TextField(blank=True),
        ),
    ]
