# Generated by Django 4.1.7 on 2023-03-20 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallpapers', '0008_alter_wallpaper_slug_alter_wallpaper_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Download',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='wallpaper',
            name='downloads_count',
        ),
        migrations.AddField(
            model_name='wallpaper',
            name='downloads',
            field=models.ManyToManyField(to='wallpapers.download'),
        ),
    ]
