# Generated by Django 4.1.7 on 2023-03-20 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallpapers', '0009_download_remove_wallpaper_downloads_count_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallpaper',
            name='downloads',
        ),
        migrations.AddField(
            model_name='download',
            name='wallpaper',
            field=models.ManyToManyField(to='wallpapers.wallpaper'),
        ),
    ]
