# Generated by Django 4.1.7 on 2023-03-20 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wallpapers', '0010_remove_wallpaper_downloads_download_wallpaper'),
    ]

    operations = [
        migrations.AddField(
            model_name='download',
            name='count',
            field=models.IntegerField(default=1),
        ),
        migrations.RemoveField(
            model_name='download',
            name='wallpaper',
        ),
        migrations.AddField(
            model_name='download',
            name='wallpaper',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='wallpapers.wallpaper'),
            preserve_default=False,
        ),
    ]
