# Generated by Django 4.1.7 on 2023-03-20 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallpapers', '0011_download_count_remove_download_wallpaper_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='download',
            name='count',
        ),
    ]
